workflows:
    sample-workflow:
        name: TomQRIos
        max_build_duration: 120
        instance_type: mac_mini_m2
        environment:
          ios_signing:
            distribution_type: app_store  # or: ad_hoc | development | enterprise
            bundle_identifier: com.oslo.qrtest
        publishing:
          app_store_connect:
            # Use referenced App Store Connect API key to authenticate binary upload
            auth: integration 
    
            # Configuration related to TestFlight (optional)
    
            # Optional boolean, defaults to false. Whether or not to submit the uploaded
            # build to TestFlight beta review.
            # Note: This action is performed during post-processing.
            submit_to_testflight: true
    
            # Optional boolean, defaults to false. Set to true to automatically expire 
            # previous build in review or waiting for review in Testflight before
            # submitting a new build to beta review. Expired builds will no longer be available for testers.
            # Note: This action is performed during post-processing.
            expire_build_submitted_for_review: true
    
           
            # Configuration related to App Store (optional)
    
            # Optional boolean, defaults to false. Whether or not to submit the uploaded
            # build to App Store review. Note: This action is performed during post-processing.
            submit_to_app_store: true
    
            # Optional boolean, defaults to false. Set to true to cancel the previous 
            # submission (if applicable) when submitting a new build to App Store review.
            # This allows automatically submitting a new build for review if a previous submission exists.
            # Note: This action is performed during post-processing.
            cancel_previous_submissions: true
            
            # Optional, defaults to MANUAL. Supported values: MANUAL, AFTER_APPROVAL or SCHEDULED
            release_type: SCHEDULED
    
            # Optional. Timezone-aware ISO8601 timestamp with hour precision when scheduling
            # the release. This can be only used when release type is set to SCHEDULED.
            # It cannot be set to a date in the past.
            earliest_release_date: 2021-12-01T14:00:00+00:00 
            
            # Optional. The name of the person or entity that owns the exclusive rights
            # to your app, preceded by the year the rights were obtained.
            copyright: 2021 Nevercode Ltd
    
            # Optional boolean. Whether or not to release an App Store version update in phases.
            # With this option turned on, your version update will be released over a 7-day period
            # to a percentage of your users (selected at random by their Apple ID) with automatic
            # updates turned on. Learn more from 
            # https://developer.apple.com/help/app-store-connect/update-your-app/release-a-version-update-in-phases.
            # If not specified, then App Store version default phased release configuration is reused.
            phased_release: true
