workflows:
    sample-workflow:
        name: TomQRIos
        max_build_duration: 120
        instance_type: mac_mini_m2
        environment:
          ios_signing:
            distribution_type: appstore  # or: ad_hoc | development | enterprise
            bundle_identifier: com.oslo.qrtest
